{{- if not .Values.opnsense.existingSecret -}}
{{- if or .Values.opnsense.apiKey .Values.opnsense.apiSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "operator.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.opnsense.apiKey | quote }}
  api-secret: {{ .Values.opnsense.apiSecret | quote }}
{{- end }}
{{- end }}
